name: create release package

on:
  workflow_dispatch:
  release:
    types: [created]
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
env:
  RELEASEVERSION: ${{ github.ref_name }}

jobs:
 package:
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v4
      
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install devtools
        run: |
          install.packages("devtools")
        shell: Rscript {0}

      - name: Build package
        run: |
          devtools::build(getwd())
        shell: Rscript {0}

# Publish Package as a Release
      - name: find build package
        if: github.event_name == 'release'
        run: |
          echo PACKAGE=../rstr_*.tar.gz >> $GITHUB_ENV

      - name: Publish ${{ env.Package }}
        if: github.event_name == 'release'
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: ${{ env.PACKAGE }} 
          tag: ${{ env.RELEASEVERSION }}        
          allowUpdates: true
        
